# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findORFsFastaCpp <- function(fastaSeqs, startCodon, stopCodon, minimumLength, isCircular, plusStrandOnly) {
    .Call(`_DOTSeq_findORFsFastaCpp`, fastaSeqs, startCodon, stopCodon, minimumLength, isCircular, plusStrandOnly)
}

orfs_as_IRanges <- function(main_string, s, e, minimumLength) {
    .Call(`_DOTSeq_orfs_as_IRanges`, main_string, s, e, minimumLength)
}

